# 1. Introduction

In this guided project I'll be working with a dataset of used cars from eBay Kleinanzeigen. This a classfieds section of the German eBay website.

The dataset that I'll be working with was originally scraped and uploaded to Kaggle. There are a few modifications from the original dataset th was uploaded to Kaggle:

    . 50,000 data points from the full dataset were sampled to ensure the code runs more quickly.

    . The dataset is dirtied a bit to more closely resemble what you would expect from a scraped dataset.

### Data Dictionary provided with data is as follows:

. dateCrawled - When this ad was first crawled. All field-values are taken form this date.

. name - Name of the car.

. seller - whether the seller is private or a dealer.

. offerType - The type of listing

. price - The price on the ad to sell the car.

. abtest - Whether the listing is included in an A/B test.

. vehicleType - The vehicle Type.

. yearOfRegistration - The year in which the car was first registered.

. gearbox - The transmission type.

. powerPS - The power of the car in PS.

. model - The car model name.

. kilometer - How many kilometers the car has driven.

. monthOfRegistration - The month in which the car was first 
registered.

. fuelType - What tyep of fuel the car uses.

. brand - The rand of the car.

. notRepairedDamage - If the car has a damage which is not yet repaired.

. dateCreated - The date on which the eBay listing was created.

. nrOfPictures - The number of picture in the ad.

. postalCode - the postal code for the location of the vehicle.

. lastSeenOnline - When the crawler saw this ad last online.

### Goals of project:

-> Clean data and analyze the included used car listings.

-> Become familiar with some of the unique benefits jupyter notebook provides for pandas

In [1]:
import pandas as pd
autos = pd.read_csv("autos.csv", index_col=0, encoding ="Latin-1")

In [2]:
# jupyter has the ability to render the first few 
# and last few lines of any panda object

autos

,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
dateCrawled,,,,,,,,,,,,,,,,,,,
2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [3]:
autos.info()
autos.head()

<class 'pandas.core.frame.DataFrame'>
Index: 50000 entries, 2016-03-26 17:47:46 to 2016-03-14 00:42:12
Data columns (total 19 columns):
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(14)
memory usage: 7.6+ MB

,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
dateCrawled,,,,,,,,,,,,,,,,,,,
2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

Looking at the info we see that most data are object i.e. strings or integers types. There are quite a bit of null values in the vehicleType, gearbox, model, fuelType, and notRepairedDamage columns.

# 2. Cleaning Column Names

Some more observations we can make are that the atatset contains 20 columns, 15 of those are strings. Some columns have null values, but none have more than ~20% null values. The column name follow the camelcase format instead of snakecase which means we can't just replace spaces with underscores.

We are going to convert the column names from camelcase to snakecase and reword some of the column names based on the data dictionary to be more descriptive.

In [4]:
autos.columns

new_columns = ['name', 'seller', 'offer_type', 'price', 'ab_test', 
              'vehicle_type', 'registration_year', 'gearbox', 'power_ps',
              'model', 'odometer', 'registration_month', 'fuel_type', 'brand',
              'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
              'last_seen'
             ]

autos.columns = new_columns

autos.head

<bound method NDFrame.head of                                                                   name  \
dateCrawled
2016-03-26 17:47:46                   Peugeot_807_160_NAVTECH_ON_BOARD
2016-04-04 13:38:56         BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik
2016-03-26 18:57:24                         Volkswagen_Golf_1.6_United
2016-03-12 16:58:10  Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...
2016-04-01 14:38:50  Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...
2016-03-21 13:47:45  Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...
2016-03-20 17:55:21  VW_Golf_III_GT_Special_Electronic_Green_Metall...
2016-03-16 18:55:19                               Golf_IV_1.9_TDI_90PS
2016-03-22 16:51:34                                         Seat_Arosa
2016-03-16 13:47:02          Renault_Megane_Scenic_1.6e_RT_Klimaanlage
2016-03-15 01:41:36                       VW_Golf_Tuning_in_siber/grau
2016-03-16 18:45:34                         Mercedes_A140_Motorschaden
2016-03-31 19:48:22  Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...
2016-03-23 10:48:32                                 Audi_A3_1.6_tuning
2016-03-23 11:50:46  Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...
2016-04-01 12:06:20        Corvette_C3_Coupe_T_Top_Crossfire_Injection
2016-03-16 14:59:02                                Opel_Vectra_B_Kombi
2016-03-29 11:46:22                          Volkswagen_Scirocco_2_G60
2016-03-26 19:57:44               Verkaufen_mein_bmw_e36_320_i_touring
2016-03-17 13:36:21        mazda_tribute_2.0_mit_gas_und_tuev_neu_2018
2016-03-05 19:57:31  Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...
2016-03-06 19:07:10                      Porsche_911_Carrera_4S_Cabrio
2016-03-28 20:50:54                               MINI_Cooper_S_Cabrio
2016-03-10 19:55:34   Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima
2016-04-03 11:57:02                         BMW_535i_xDrive_Sport_Aut.
2016-03-21 21:56:18  Ford_escort_kombi_an_bastler_mit_ghia_ausstattung
2016-04-03 22:46:28                                Volkswagen_Polo_Fox
2016-03-27 18:45:01             Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE
2016-03-19 21:56:19                                      MINI_Cooper_D
2016-04-02 12:45:44  Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...
...                                                                ...
2016-03-21 22:47:37  c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...
2016-03-29 14:54:12                                         W.Lupo_1.0
2016-03-26 22:25:23          Mercedes_Benz_Vito_115_CDI_Extralang_Aut.
2016-03-27 05:32:39                   Mercedes_Benz_SLK_200_Kompressor
2016-03-20 10:52:31  Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...
2016-03-27 20:51:39          Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort
2016-03-19 18:56:05  Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...
2016-03-31 18:37:18                        Mercedes_Benz_C200_Cdi_W203
2016-04-04 10:37:14                        Mercedes_Benz_E_200_Classic
2016-03-20 18:38:40                      Volkswagen_Polo_1.6_TDI_Style
2016-03-12 10:55:54                            Ford_Escort_Turnier_16V
2016-03-15 09:38:21             Opel_Astra_Kombi_mit_Anhaengerkupplung
2016-03-29 18:51:08            Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm
2016-03-06 12:43:04                                      Ford_focus_99
2016-03-31 22:48:48  Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...
2016-04-02 16:38:23                          Verkaufe_meinen_vw_vento!
2016-04-04 20:46:02  Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...
2016-03-22 20:47:27  Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...
2016-03-28 19:49:51                                         BMW_330_Ci
2016-03-11 19:50:37        VW_Polo_zum_Ausschlachten_oder_Wiederaufbau
2016-03-21 19:54:19         Mercedes_Benz_A_200__BlueEFFICIENCY__Urban
2016-03-06 15:25:19                                         Kleinwagen
2016-03-10 19:37:38              Fiat_Grande_Punto_1.4_T_Jet_16V_Sport
2016-03-15 18:47:35           Audi_A3__1_8l__Silber;_schoenes_Fahrzeug
2016-03-22 17:36:42  Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...
2016-03-27 14:38:19   Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon
2016-03-28 10:50:25  Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...
2016-04-02 14:44:48                     Fiat_500_C_1.2_Dualogic_Lounge
2016-03-08 19:25:42                 Audi_A3_2.0_TDI_Sportback_Ambition
2016-03-14 00:42:12                                Opel_Vectra_1.6_16V

                     seller offer_type    price  ab_test vehicle_type  \
dateCrawled
2016-03-26 17:47:46  privat    Angebot   $5,000  control          bus
2016-04-04 13:38:56  privat    Angebot   $8,500  control    limousine
2016-03-26 18:57:24  privat    Angebot   $8,990     test    limousine
2016-03-12 16:58:10  privat    Angebot   $4,350  control   kleinwagen
2016-04-01 14:38:50  privat    Angebot   $1,350     test        kombi
2016-03-21 13:47:45  privat    Angebot   $7,900     test          bus
2016-03-20 17:55:21  privat    Angebot     $300     test    limousine
2016-03-16 18:55:19  privat    Angebot   $1,990  control    limousine
2016-03-22 16:51:34  privat    Angebot     $250     test          NaN
2016-03-16 13:47:02  privat    Angebot     $590  control          bus
2016-03-15 01:41:36  privat    Angebot     $999     test          NaN
2016-03-16 18:45:34  privat    Angebot     $350  control          NaN
2016-03-31 19:48:22  privat    Angebot   $5,299  control   kleinwagen
2016-03-23 10:48:32  privat    Angebot   $1,350  control    limousine
2016-03-23 11:50:46  privat    Angebot   $3,999     test   kleinwagen
2016-04-01 12:06:20  privat    Angebot  $18,900     test        coupe
2016-03-16 14:59:02  privat    Angebot     $350     test        kombi
2016-03-29 11:46:22  privat    Angebot   $5,500     test        coupe
2016-03-26 19:57:44  privat    Angebot     $300  control          bus
2016-03-17 13:36:21  privat    Angebot   $4,150  control          suv
2016-03-05 19:57:31  privat    Angebot   $3,500     test        kombi
2016-03-06 19:07:10  privat    Angebot  $41,500     test       cabrio
2016-03-28 20:50:54  privat    Angebot  $25,450  control       cabrio
2016-03-10 19:55:34  privat    Angebot   $7,999  control          bus
2016-04-03 11:57:02  privat    Angebot  $48,500  control    limousine
2016-03-21 21:56:18  privat    Angebot      $90  control        kombi
2016-04-03 22:46:28  privat    Angebot     $777  control   kleinwagen
2016-03-27 18:45:01  privat    Angebot       $0  control          NaN
2016-03-19 21:56:19  privat    Angebot   $5,250  control   kleinwagen
2016-04-02 12:45:44  privat    Angebot   $4,999     test        kombi
...                     ...        ...      ...      ...          ...
2016-03-21 22:47:37  privat    Angebot  $15,800  control          bus
2016-03-29 14:54:12  privat    Angebot     $950     test   kleinwagen
2016-03-26 22:25:23  privat    Angebot   $3,300  control          bus
2016-03-27 05:32:39  privat    Angebot   $6,000  control       cabrio
2016-03-20 10:52:31  privat    Angebot       $0  control       cabrio
2016-03-27 20:51:39  privat    Angebot   $9,700  control   kleinwagen
2016-03-19 18:56:05  privat    Angebot   $5,900     test        kombi
2016-03-31 18:37:18  privat    Angebot   $5,500  control    limousine
2016-04-04 10:37:14  privat    Angebot     $900  control    limousine
2016-03-20 18:38:40  privat    Angebot  $11,000     test   kleinwagen
2016-03-12 10:55:54  privat    Angebot     $400  control        kombi
2016-03-15 09:38:21  privat    Angebot   $2,000  control        kombi
2016-03-29 18:51:08  privat    Angebot   $1,950  control   kleinwagen
2016-03-06 12:43:04  privat    Angebot     $600     test   kleinwagen
2016-03-31 22:48:48  privat    Angebot       $0     test          NaN
2016-04-02 16:38:23  privat    Angebot   $1,000  control          NaN
2016-04-04 20:46:02  privat    Angebot  $15,900  control    limousine
2016-03-22 20:47:27  privat    Angebot  $21,990  control    limousine
2016-03-28 19:49:51  privat    Angebot   $9,550  control        coupe
2016-03-11 19:50:37  privat    Angebot     $150     test   kleinwagen
2016-03-21 19:54:19  privat    Angebot  $17,500     test    limousine
2016-03-06 15:25:19  privat    Angebot     $500  control          NaN
2016-03-10 19:37:38  privat    Angebot   $4,800  control   kleinwagen
2016-03-15 18:47:35  privat    Angebot   $1,650  control   kleinwagen
2016-03-22 17:36:42  privat    Angebot   $5,000  control        kombi
2016-03-27 14:38:19  privat    Angebot  $24,900  control    limousine
2016-03-28 10:50:25  privat    Angebot   $1,980  control       cabrio
2016-04-02 14:44:48  privat    Angebot  $13,200     test       cabrio
2016-03-08 19:25:42  privat    Angebot  $22,900  control        kombi
2016-03-14 00:42:12  privat    Angebot   $1,250  control    limousine

                     registration_year    gearbox  power_ps     model  \
dateCrawled
2016-03-26 17:47:46               2004    manuell       158    andere
2016-04-04 13:38:56               1997  automatik       286       7er
2016-03-26 18:57:24               2009    manuell       102      golf
2016-03-12 16:58:10               2007  automatik        71    fortwo
2016-04-01 14:38:50               2003    manuell         0     focus
2016-03-21 13:47:45               2006  automatik       150   voyager
2016-03-20 17:55:21               1995    manuell        90      golf
2016-03-16 18:55:19               1998    manuell        90      golf
2016-03-22 16:51:34               2000    manuell         0     arosa
2016-03-16 13:47:02               1997    manuell        90    megane
2016-03-15 01:41:36               2017    manuell        90       NaN
2016-03-16 18:45:34               2000        NaN         0       NaN
2016-03-31 19:48:22               2010  automatik        71    fortwo
2016-03-23 10:48:32               1999    manuell       101        a3
2016-03-23 11:50:46               2007    manuell        75      clio
2016-04-01 12:06:20               1982  automatik       203       NaN
2016-03-16 14:59:02               1999    manuell       101    vectra
2016-03-29 11:46:22               1990    manuell       205  scirocco
2016-03-26 19:57:44               1995    manuell       150       3er
2016-03-17 13:36:21               2004    manuell       124    andere
2016-03-05 19:57:31               2003    manuell       131        a4
2016-03-06 19:07:10               2004    manuell       320       911
2016-03-28 20:50:54               2015    manuell       184    cooper
2016-03-10 19:55:34               2010    manuell       120       NaN
2016-04-03 11:57:02               2014  automatik       306       5er
2016-03-21 21:56:18               1996    manuell       116       NaN
2016-04-03 22:46:28               1992    manuell        54      polo
2016-03-27 18:45:01               2005        NaN         0       NaN
2016-03-19 21:56:19               2007    manuell       110    cooper
2016-04-02 12:45:44               2004  automatik       204  e_klasse
...                                ...        ...       ...       ...
2016-03-21 22:47:37               2010  automatik       136        c4
2016-03-29 14:54:12               2001    manuell        50      lupo
2016-03-26 22:25:23               2004  automatik       150      vito
2016-03-27 05:32:39               2004    manuell       163       slk
2016-03-20 10:52:31               1983    manuell        70      golf
2016-03-27 20:51:39               2012  automatik        88      jazz
2016-03-19 18:56:05               1992  automatik       150        80
2016-03-31 18:37:18               2003    manuell       116  c_klasse
2016-04-04 10:37:14               1996  automatik       136  e_klasse
2016-03-20 18:38:40               2011    manuell        90      polo
2016-03-12 10:55:54               1995    manuell       105    escort
2016-03-15 09:38:21               1998    manuell       115     astra
2016-03-29 18:51:08               2004    manuell         0     fabia
2016-03-06 12:43:04               1999    manuell       101     focus
2016-03-31 22:48:48               2000        NaN         0       NaN
2016-04-02 16:38:23               1995  automatik         0       NaN
2016-04-04 20:46:02               2010  automatik       218      300c
2016-03-22 20:47:27               2013    manuell       150        a3
2016-03-28 19:49:51               2001    manuell       231       3er
2016-03-11 19:50:37               1997    manuell         0      polo
2016-03-21 19:54:19               2012    manuell       156  a_klasse
2016-03-06 15:25:19               2016    manuell         0    twingo
2016-03-10 19:37:38               2009    manuell       120    andere
2016-03-15 18:47:35               1997    manuell         0       NaN
2016-03-22 17:36:42               2001  automatik       299        a6
2016-03-27 14:38:19               2011  automatik       239        q5
2016-03-28 10:50:25               1996    manuell        75     astra
2016-04-02 14:44:48               2014  automatik        69       500
2016-03-08 19:25:42               2013    manuell       150        a3
2016-03-14 00:42:12               1996    manuell       101    vectra

                      odometer  registration_month fuel_type           brand  \
dateCrawled
2016-03-26 17:47:46  150,000km                   3       lpg         peugeot
2016-04-04 13:38:56  150,000km                   6    benzin             bmw
2016-03-26 18:57:24   70,000km                   7    benzin      volkswagen
2016-03-12 16:58:10   70,000km                   6    benzin           smart
2016-04-01 14:38:50  150,000km                   7    benzin            ford
2016-03-21 13:47:45  150,000km                   4    diesel        chrysler
2016-03-20 17:55:21  150,000km                   8    benzin      volkswagen
2016-03-16 18:55:19  150,000km                  12    diesel      volkswagen
2016-03-22 16:51:34  150,000km                  10       NaN            seat
2016-03-16 13:47:02  150,000km                   7    benzin         renault
2016-03-15 01:41:36  150,000km                   4    benzin      volkswagen
2016-03-16 18:45:34  150,000km                   0    benzin   mercedes_benz
2016-03-31 19:48:22   50,000km                   9    benzin           smart
2016-03-23 10:48:32  150,000km                  11    benzin            audi
2016-03-23 11:50:46  150,000km                   9    benzin         renault
2016-04-01 12:06:20   80,000km                   6    benzin  sonstige_autos
2016-03-16 14:59:02  150,000km                   5    benzin            opel
2016-03-29 11:46:22  150,000km                   6    benzin      volkswagen
2016-03-26 19:57:44  150,000km                   0    benzin             bmw
2016-03-17 13:36:21  150,000km                   2       lpg           mazda
2016-03-05 19:57:31  150,000km                   5    diesel            audi
2016-03-06 19:07:10  150,000km                   4    benzin         porsche
2016-03-28 20:50:54   10,000km                   1    benzin            mini
2016-03-10 19:55:34  150,000km                   2    diesel         peugeot
2016-04-03 11:57:02   30,000km                  12    benzin             bmw
2016-03-21 21:56:18  150,000km                   4    benzin            ford
2016-04-03 22:46:28  125,000km                   2    benzin      volkswagen
2016-03-27 18:45:01  150,000km                   0       NaN            ford
2016-03-19 21:56:19  150,000km                   7    diesel            mini
2016-04-02 12:45:44  150,000km                  10    diesel   mercedes_benz
...                        ...                 ...       ...             ...
2016-03-21 22:47:37   60,000km                   4    diesel         citroen
2016-03-29 14:54:12  150,000km                   4    benzin      volkswagen
2016-03-26 22:25:23  150,000km                  10    diesel   mercedes_benz
2016-03-27 05:32:39  150,000km                  11    benzin   mercedes_benz
2016-03-20 10:52:31  150,000km                   2    benzin      volkswagen
2016-03-27 20:51:39  100,000km                  11    hybrid           honda
2016-03-19 18:56:05  150,000km                  12    benzin            audi
2016-03-31 18:37:18  150,000km                   2    diesel   mercedes_benz
2016-04-04 10:37:14  150,000km                   9    benzin   mercedes_benz
2016-03-20 18:38:40   70,000km                  11    diesel      volkswagen
2016-03-12 10:55:54  125,000km                   3    benzin            ford
2016-03-15 09:38:21  150,000km                  12    benzin            opel
2016-03-29 18:51:08   90,000km                   7    benzin           skoda
2016-03-06 12:43:04  150,000km                   4    benzin            ford
2016-03-31 22:48:48  150,000km                   0       NaN  sonstige_autos
2016-04-02 16:38:23  150,000km                   0    benzin      volkswagen
2016-04-04 20:46:02  125,000km                  11    diesel        chrysler
2016-03-22 20:47:27   50,000km                  11    diesel            audi
2016-03-28 19:49:51  150,000km                  10    benzin             bmw
2016-03-11 19:50:37  150,000km                   5    benzin      volkswagen
2016-03-21 19:54:19   30,000km                  12    benzin   mercedes_benz
2016-03-06 15:25:19  150,000km                   0    benzin         renault
2016-03-10 19:37:38  125,000km                   9       lpg            fiat
2016-03-15 18:47:35  150,000km                   7    benzin            audi
2016-03-22 17:36:42  150,000km                   1    benzin            audi
2016-03-27 14:38:19  100,000km                   1    diesel            audi
2016-03-28 10:50:25  150,000km                   5    benzin            opel
2016-04-02 14:44:48    5,000km                  11    benzin            fiat
2016-03-08 19:25:42   40,000km                  11    diesel            audi
2016-03-14 00:42:12  150,000km                   1    benzin            opel

                    unrepaired_damage           ad_created  nr_of_pictures  \
dateCrawled
2016-03-26 17:47:46              nein  2016-03-26 00:00:00               0
2016-04-04 13:38:56              nein  2016-04-04 00:00:00               0
2016-03-26 18:57:24              nein  2016-03-26 00:00:00               0
2016-03-12 16:58:10              nein  2016-03-12 00:00:00               0
2016-04-01 14:38:50              nein  2016-04-01 00:00:00               0
2016-03-21 13:47:45               NaN  2016-03-21 00:00:00               0
2016-03-20 17:55:21               NaN  2016-03-20 00:00:00               0
2016-03-16 18:55:19              nein  2016-03-16 00:00:00               0
2016-03-22 16:51:34              nein  2016-03-22 00:00:00               0
2016-03-16 13:47:02              nein  2016-03-16 00:00:00               0
2016-03-15 01:41:36              nein  2016-03-14 00:00:00               0
2016-03-16 18:45:34               NaN  2016-03-16 00:00:00               0
2016-03-31 19:48:22              nein  2016-03-31 00:00:00               0
2016-03-23 10:48:32              nein  2016-03-23 00:00:00               0
2016-03-23 11:50:46               NaN  2016-03-23 00:00:00               0
2016-04-01 12:06:20              nein  2016-04-01 00:00:00               0
2016-03-16 14:59:02              nein  2016-03-16 00:00:00               0
2016-03-29 11:46:22              nein  2016-03-29 00:00:00               0
2016-03-26 19:57:44               NaN  2016-03-26 00:00:00               0
2016-03-17 13:36:21              nein  2016-03-17 00:00:00               0
2016-03-05 19:57:31               NaN  2016-03-05 00:00:00               0
2016-03-06 19:07:10              nein  2016-03-06 00:00:00               0
2016-03-28 20:50:54              nein  2016-03-28 00:00:00               0
2016-03-10 19:55:34              nein  2016-03-10 00:00:00               0
2016-04-03 11:57:02              nein  2016-04-03 00:00:00               0
2016-03-21 21:56:18                ja  2016-03-21 00:00:00               0

# 3. Initial Exploration and Cleaning

We'll explore the data a bit more to see what other cleaning tasks need to be done. So we'll start by looking for tesxt columns where all or almost all values are the same. These can often be dropped as they don't have sueful information for analysis. We'll look for examples of numeric data stored as text which can be cleaned and converted.

In [5]:
autos.describe(include='all')

,name,seller,offer_type,price,ab_test,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

Notes:

-> The columsn with too few values are seller, offer type, ab_test, gearbox, unrepaired damage

-> The columns that need more investigation are vehicle_type, registration_year, power_ps, odometer, registration month, fue_type, brand, nr_of_pictures, and postal_code.

-> The columns that have are stored as text that need to be cleaned are price, and odometer.

-> The columns that I'm a bit uncertain about are registration_year, power_ps, registration_month, nr_of_pictures, postal_code, and unrepaired_damage.

So the price and odometer columns can be cleaned relatively easily. So we'll take of those type by removing any non-numeric characters, convert the column to a numeric dtype, and rename them appropriately.

In [6]:
autos['price'] = autos['price'].str.replace(",","")
autos['price'] = autos['price'].str.replace("$","")
autos['price'] = autos['price'].astype(int)
autos['odometer'] = autos['odometer'].str.replace(",","")
autos['odometer'] = autos['odometer'].str.replace("km","")
autos['odometer'] = autos['odometer'].astype(int)

In [9]:
autos.rename({'odometer':'odometer_km'}, axis = 1, inplace = True)

In [12]:
autos['price']

dateCrawled
2016-03-26 17:47:46     5000
2016-04-04 13:38:56     8500
2016-03-26 18:57:24     8990
2016-03-12 16:58:10     4350
2016-04-01 14:38:50     1350
2016-03-21 13:47:45     7900
2016-03-20 17:55:21      300
2016-03-16 18:55:19     1990
2016-03-22 16:51:34      250
2016-03-16 13:47:02      590
2016-03-15 01:41:36      999
2016-03-16 18:45:34      350
2016-03-31 19:48:22     5299
2016-03-23 10:48:32     1350
2016-03-23 11:50:46     3999
2016-04-01 12:06:20    18900
2016-03-16 14:59:02      350
2016-03-29 11:46:22     5500
2016-03-26 19:57:44      300
2016-03-17 13:36:21     4150
2016-03-05 19:57:31     3500
2016-03-06 19:07:10    41500
2016-03-28 20:50:54    25450
2016-03-10 19:55:34     7999
2016-04-03 11:57:02    48500
2016-03-21 21:56:18       90
2016-04-03 22:46:28      777
2016-03-27 18:45:01        0
2016-03-19 21:56:19     5250
2016-04-02 12:45:44     4999
                       ...
2016-03-21 22:47:37    15800
2016-03-29 14:54:12      950
2016-03-26 22:25:23     3300
2016-03-27 05:32:39     6000
2016-03-20 10:52:31        0
2016-03-27 20:51:39     9700
2016-03-19 18:56:05     5900
2016-03-31 18:37:18     5500
2016-04-04 10:37:14      900
2016-03-20 18:38:40    11000
2016-03-12 10:55:54      400
2016-03-15 09:38:21     2000
2016-03-29 18:51:08     1950
2016-03-06 12:43:04      600
2016-03-31 22:48:48        0
2016-04-02 16:38:23     1000
2016-04-04 20:46:02    15900
2016-03-22 20:47:27    21990
2016-03-28 19:49:51     9550
2016-03-11 19:50:37      150
2016-03-21 19:54:19    17500
2016-03-06 15:25:19      500
2016-03-10 19:37:38     4800
2016-03-15 18:47:35     1650
2016-03-22 17:36:42     5000
2016-03-27 14:38:19    24900
2016-03-28 10:50:25     1980
2016-04-02 14:44:48    13200
2016-03-08 19:25:42    22900
2016-03-14 00:42:12     1250
Name: price, Length: 50000, dtype: int64

In [14]:
autos['odometer_km']

dateCrawled
2016-03-26 17:47:46    150000
2016-04-04 13:38:56    150000
2016-03-26 18:57:24     70000
2016-03-12 16:58:10     70000
2016-04-01 14:38:50    150000
2016-03-21 13:47:45    150000
2016-03-20 17:55:21    150000
2016-03-16 18:55:19    150000
2016-03-22 16:51:34    150000
2016-03-16 13:47:02    150000
2016-03-15 01:41:36    150000
2016-03-16 18:45:34    150000
2016-03-31 19:48:22     50000
2016-03-23 10:48:32    150000
2016-03-23 11:50:46    150000
2016-04-01 12:06:20     80000
2016-03-16 14:59:02    150000
2016-03-29 11:46:22    150000
2016-03-26 19:57:44    150000
2016-03-17 13:36:21    150000
2016-03-05 19:57:31    150000
2016-03-06 19:07:10    150000
2016-03-28 20:50:54     10000
2016-03-10 19:55:34    150000
2016-04-03 11:57:02     30000
2016-03-21 21:56:18    150000
2016-04-03 22:46:28    125000
2016-03-27 18:45:01    150000
2016-03-19 21:56:19    150000
2016-04-02 12:45:44    150000
                        ...
2016-03-21 22:47:37     60000
2016-03-29 14:54:12    150000
2016-03-26 22:25:23    150000
2016-03-27 05:32:39    150000
2016-03-20 10:52:31    150000
2016-03-27 20:51:39    100000
2016-03-19 18:56:05    150000
2016-03-31 18:37:18    150000
2016-04-04 10:37:14    150000
2016-03-20 18:38:40     70000
2016-03-12 10:55:54    125000
2016-03-15 09:38:21    150000
2016-03-29 18:51:08     90000
2016-03-06 12:43:04    150000
2016-03-31 22:48:48    150000
2016-04-02 16:38:23    150000
2016-04-04 20:46:02    125000
2016-03-22 20:47:27     50000
2016-03-28 19:49:51    150000
2016-03-11 19:50:37    150000
2016-03-21 19:54:19     30000
2016-03-06 15:25:19    150000
2016-03-10 19:37:38    125000
2016-03-15 18:47:35    150000
2016-03-22 17:36:42    150000
2016-03-27 14:38:19    100000
2016-03-28 10:50:25    150000
2016-04-02 14:44:48      5000
2016-03-08 19:25:42     40000
2016-03-14 00:42:12    150000
Name: odometer_km, Length: 50000, dtype: int64

# 4. Exploring the Odometer and Price Columns

We can observe that almost all the values of specific columns like seller and offer_type are the same.

I was  able to convert price and odometer to numeric types and rename odometer to odometer_km.

Now the goal is to explore the data a bit further to see what doesn't make sense and we can continue with the price and odometer_km columns.
We'll do this by analyzing the columns using minimum and maximum values and looking for any values that look unrealistically high or low (outliers) that we might want to remove.

In [38]:
autos['odometer_km'].unique().shape

(13,)

In [39]:
autos['odometer_km'].describe()

count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [40]:
autos['odometer_km'].value_counts().sort_index(ascending=True)

5000        967
10000       264
20000       784
30000       789
40000       819
50000      1027
60000      1164
70000      1230
80000      1436
90000      1757
100000     2169
125000     5170
150000    32424
Name: odometer_km, dtype: int64

Looking at the unique values we can see that there aren't any outliers in the odometer_km column

In [41]:
autos['price'].unique().shape

(2357,)

In [43]:
autos['price'].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

In [45]:
autos['price'].value_counts().sort_index(ascending=True)

0           1421
1            156
2              3
3              1
5              2
8              1
9              1
10             7
11             2
12             3
13             2
14             1
15             2
17             3
18             1
20             4
25             5
29             1
30             7
35             1
40             6
45             4
47             1
49             4
50            49
55             2
59             1
60             9
65             5
66             1
            ...
151990         1
155000         1
163500         1
163991         1
169000         1
169999         1
175000         1
180000         1
190000         1
194000         1
197000         1
198000         1
220000         1
250000         1
259000         1
265000         1
295000         1
299000         1
345000         1
350000         1
999990         1
999999         2
1234566        1
1300000        1
3890000        1
10000000       1
11111111       2
12345678       3
27322222       1
99999999       1
Name: price, Length: 2357, dtype: int64